// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void walking_Animation( lv_obj_t *TargetObject, int delay);
void thumbsup_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Tab_main;
extern lv_obj_t *ui_stat;
extern lv_obj_t *ui_Tab_main1;
extern lv_obj_t *ui_tab_time;
extern lv_obj_t *ui_Label_Time;
extern lv_obj_t *ui_Bar_Temp;
extern lv_obj_t *ui_Bar_Hum;
extern lv_obj_t *ui_Label_01;
extern lv_obj_t *ui_Label_1;
extern lv_obj_t *ui_Label_4;
extern lv_obj_t *ui_Label_5;
extern lv_obj_t *ui_Label_6;
extern lv_obj_t *ui_Label_7;
extern lv_obj_t *ui_Label_8;
extern lv_obj_t *ui_Label_9;
extern lv_obj_t *ui_Image_time;
extern lv_obj_t *ui_tab_weather;
extern lv_obj_t *ui_Label_temp;
extern lv_obj_t *ui_Label_hum;
extern lv_obj_t *ui_Label_condition;
extern lv_obj_t *ui_Label_windkph;
extern lv_obj_t *ui_Image_compass;
extern lv_obj_t *ui_Label_3;
extern lv_obj_t *ui_Bar_FL;
extern lv_obj_t *ui_Bar_HI;
extern lv_obj_t *ui_Label_2;
extern lv_obj_t *ui_Label_10;
extern lv_obj_t *ui_Label_11;
extern lv_obj_t *ui_Label_12;
extern lv_obj_t *ui_Label_13;
extern lv_obj_t *ui_Label_14;
extern lv_obj_t *ui_Label_15;
extern lv_obj_t *ui_Image_weather;
extern lv_obj_t *ui_Panel_date;
extern lv_obj_t *ui_Label_date;
extern lv_obj_t *ui_Panel_battery;
extern lv_obj_t *ui_Bar_battery;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_tab_data;
extern lv_obj_t *ui_Label_battery;
extern lv_obj_t *ui_Image_data;
extern lv_obj_t *ui_TextArea_Data;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_images_button_checked_png);   // assets/Images/button_checked.png
LV_IMG_DECLARE( ui_img_images_walking_png_frames_walking_000_png);   // assets/Images/walking_png_frames/walking_000.png
LV_IMG_DECLARE( ui_img_images_compass_png);   // assets/Images/compass.png
LV_IMG_DECLARE( ui_img_images_battery_png);   // assets/Images/battery.png
LV_IMG_DECLARE( ui_img_images_thumpsup_png_frames_thumpsup_000_png);   // assets/Images/thumpsup_png_frames/thumpsup_000.png
LV_IMG_DECLARE( ui_img_images_vault_logo_png);   // assets/Images/vault logo.png
LV_IMG_DECLARE( ui_img_images_thumpsup_png_frames_thumpsup_001_png);   // assets/Images/thumpsup_png_frames/thumpsup_001.png
LV_IMG_DECLARE( ui_img_images_thumpsup_png_frames_thumpsup_002_png);   // assets/Images/thumpsup_png_frames/thumpsup_002.png
LV_IMG_DECLARE( ui_img_images_thumpsup_png_frames_thumpsup_003_png);   // assets/Images/thumpsup_png_frames/thumpsup_003.png
LV_IMG_DECLARE( ui_img_images_thumpsup_png_frames_thumpsup_004_png);   // assets/Images/thumpsup_png_frames/thumpsup_004.png
LV_IMG_DECLARE( ui_img_images_thumpsup_png_frames_thumpsup_005_png);   // assets/Images/thumpsup_png_frames/thumpsup_005.png
LV_IMG_DECLARE( ui_img_images_thumpsup_png_frames_thumpsup_006_png);   // assets/Images/thumpsup_png_frames/thumpsup_006.png
LV_IMG_DECLARE( ui_img_images_thumpsup_png_frames_thumpsup_007_png);   // assets/Images/thumpsup_png_frames/thumpsup_007.png
LV_IMG_DECLARE( ui_img_images_thumpsup_png_frames_thumpsup_008_png);   // assets/Images/thumpsup_png_frames/thumpsup_008.png
LV_IMG_DECLARE( ui_img_images_thumpsup_png_frames_thumpsup_009_png);   // assets/Images/thumpsup_png_frames/thumpsup_009.png
LV_IMG_DECLARE( ui_img_images_thumpsup_png_frames_thumpsup_010_png);   // assets/Images/thumpsup_png_frames/thumpsup_010.png
LV_IMG_DECLARE( ui_img_images_walking_png_frames_walking_001_png);   // assets/Images/walking_png_frames/walking_001.png
LV_IMG_DECLARE( ui_img_images_walking_png_frames_walking_002_png);   // assets/Images/walking_png_frames/walking_002.png
LV_IMG_DECLARE( ui_img_images_walking_png_frames_walking_003_png);   // assets/Images/walking_png_frames/walking_003.png
LV_IMG_DECLARE( ui_img_images_walking_png_frames_walking_004_png);   // assets/Images/walking_png_frames/walking_004.png
LV_IMG_DECLARE( ui_img_images_walking_png_frames_walking_005_png);   // assets/Images/walking_png_frames/walking_005.png
LV_IMG_DECLARE( ui_img_images_walking_png_frames_walking_006_png);   // assets/Images/walking_png_frames/walking_006.png
LV_IMG_DECLARE( ui_img_images_walking_png_frames_walking_007_png);   // assets/Images/walking_png_frames/walking_007.png
LV_IMG_DECLARE( ui_img_images_walking_png_frames_walking_008_png);   // assets/Images/walking_png_frames/walking_008.png


LV_FONT_DECLARE( ui_font_J140);
LV_FONT_DECLARE( ui_font_J30);
LV_FONT_DECLARE( ui_font_J35);
LV_FONT_DECLARE( ui_font_J60);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
