// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: pip card

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void thumpsup_Animation( lv_obj_t *TargetObject, int delay);
void walking_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Tab_main;
lv_obj_t *ui_stat;
lv_obj_t *ui_Panel_date;
lv_obj_t *ui_Label_date;
lv_obj_t *ui_Panel_battery;
lv_obj_t *ui_Bar_battery;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Label_Time;
lv_obj_t *ui_Bar_FL;
lv_obj_t *ui_Bar_HI;
lv_obj_t *ui_Labe01;
lv_obj_t *ui_Labe1;
lv_obj_t *ui_Img_stat;
lv_obj_t *ui_Labe2;
lv_obj_t *ui_Labe5;
lv_obj_t *ui_data;
lv_obj_t *ui_Label_temp;
lv_obj_t *ui_Label_hum;
lv_obj_t *ui_Bar_Hum;
lv_obj_t *ui_Bar_Temp;
lv_obj_t *ui_Labe3;
lv_obj_t *ui_Labe4;
lv_obj_t *ui_Img_data;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_thumpsup_[11] = {&ui_img_images_thumpsup_thumpsup_00_png, &ui_img_images_thumpsup_thumpsup_01_png, &ui_img_images_thumpsup_thumpsup_02_png, &ui_img_images_thumpsup_thumpsup_03_png, &ui_img_images_thumpsup_thumpsup_04_png, &ui_img_images_thumpsup_thumpsup_05_png, &ui_img_images_thumpsup_thumpsup_06_png, &ui_img_images_thumpsup_thumpsup_07_png, &ui_img_images_thumpsup_thumpsup_08_png, &ui_img_images_thumpsup_thumpsup_09_png, &ui_img_images_thumpsup_thumpsup_10_png};
const lv_img_dsc_t *ui_imgset_walking_[21] = {&ui_img_images_walking_walking_00_png, &ui_img_images_walking_walking_01_png, &ui_img_images_walking_walking_02_png, &ui_img_images_walking_walking_03_png, &ui_img_images_walking_walking_04_png, &ui_img_images_walking_walking_05_png, &ui_img_images_walking_walking_06_png, &ui_img_images_walking_walking_07_png, &ui_img_images_walking_walking_08_png, &ui_img_images_walking_walking_09_png, &ui_img_images_walking_walking_10_png, &ui_img_images_walking_walking_11_png, &ui_img_images_walking_walking_12_png, &ui_img_images_walking_walking_13_png, &ui_img_images_walking_walking_14_png, &ui_img_images_walking_walking_15_png, &ui_img_images_walking_walking_16_png, &ui_img_images_walking_walking_17_png, &ui_img_images_walking_walking_18_png, &ui_img_images_walking_walking_19_png, &ui_img_images_walking_walking_20_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void thumpsup_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_thumpsup_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_thumpsup_)/(sizeof(lv_img_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1500);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame );
lv_anim_set_values(&PropertyAnimation_0, 0, 11 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame );
lv_anim_start(&PropertyAnimation_0);

}
void walking_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->imgset = (lv_img_dsc_t **)ui_imgset_walking_;
PropertyAnimation_0_user_data->imgset_size = sizeof(ui_imgset_walking_)/(sizeof(lv_img_dsc_t*));
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1400);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_frame );
lv_anim_set_values(&PropertyAnimation_0, 0, 20 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_frame );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
