// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Tab_main = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
lv_obj_set_width( ui_Tab_main, 270);
lv_obj_set_height( ui_Tab_main, 456);
lv_obj_set_align( ui_Tab_main, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Tab_main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Tab_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Tab_main, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_Tab_main), lv_color_hex(0x00C003),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_Tab_main), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_Tab_main), &ui_font_J35,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_Tab_main), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_Tab_main), 0,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_Tab_main), lv_color_hex(0x00C200),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_Tab_main), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_Tab_main), 2,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_Tab_main), LV_BORDER_SIDE_BOTTOM,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_Tab_main), lv_color_hex(0x00C003),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_Tab_main), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_Tab_main), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_Tab_main), 0,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( lv_tabview_get_tab_btns(ui_Tab_main), &ui_img_images_button_checked_png,  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_Tab_main), lv_color_hex(0x000000),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_Tab_main), 0,  LV_PART_ITEMS| LV_STATE_CHECKED);

ui_stat = lv_tabview_add_tab(ui_Tab_main, "STAT");
lv_obj_clear_flag( ui_stat, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Tab_main1 = lv_tabview_create(ui_stat, LV_DIR_TOP, 50);
lv_obj_set_width( ui_Tab_main1, 270);
lv_obj_set_height( ui_Tab_main1, 313);
lv_obj_set_x( ui_Tab_main1, 0 );
lv_obj_set_y( ui_Tab_main1, -35 );
lv_obj_set_align( ui_Tab_main1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Tab_main1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Tab_main1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Tab_main1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_Tab_main1), lv_color_hex(0xFFFFFF),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_Tab_main1), 0,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_Tab_main1), lv_color_hex(0x00C003),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_Tab_main1), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_Tab_main1), &ui_font_J35,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_Tab_main1), lv_color_hex(0x00C003),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_Tab_main1), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_Tab_main1), lv_color_hex(0x213E13),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_Tab_main1), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_Tab_main1), lv_color_hex(0x000000),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_Tab_main1), 0,  LV_PART_ITEMS| LV_STATE_CHECKED);

ui_tab_time = lv_tabview_add_tab(ui_Tab_main1, "TIME");
lv_obj_clear_flag( ui_tab_time, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_Time = lv_label_create(ui_tab_time);
lv_obj_set_width( ui_Label_Time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_Time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_Time, 0 );
lv_obj_set_y( ui_Label_Time, -74 );
lv_obj_set_align( ui_Label_Time, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_Time,"00:00");
lv_obj_set_style_text_color(ui_Label_Time, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_Time, &ui_font_J140, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar_Temp = lv_bar_create(ui_tab_time);
lv_bar_set_range(ui_Bar_Temp, 0,60);
lv_obj_set_width( ui_Bar_Temp, 15);
lv_obj_set_height( ui_Bar_Temp, 108);
lv_obj_set_x( ui_Bar_Temp, -96 );
lv_obj_set_y( ui_Bar_Temp, 50 );
lv_obj_set_align( ui_Bar_Temp, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar_Temp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_Temp, lv_color_hex(0x182D0C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_Temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar_Temp, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_Temp, lv_color_hex(0x00C200), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_Temp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Bar_Hum = lv_bar_create(ui_tab_time);
lv_obj_set_width( ui_Bar_Hum, 15);
lv_obj_set_height( ui_Bar_Hum, 108);
lv_obj_set_x( ui_Bar_Hum, 96 );
lv_obj_set_y( ui_Bar_Hum, 50 );
lv_obj_set_align( ui_Bar_Hum, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar_Hum, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_Hum, lv_color_hex(0x182D0C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_Hum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar_Hum, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_Hum, lv_color_hex(0x00C200), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_Hum, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label_01 = lv_label_create(ui_tab_time);
lv_obj_set_width( ui_Label_01, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_01, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_01, -95 );
lv_obj_set_y( ui_Label_01, 118 );
lv_obj_set_align( ui_Label_01, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_01,"T");
lv_obj_set_style_text_color(ui_Label_01, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_01, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_01, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_1 = lv_label_create(ui_tab_time);
lv_obj_set_width( ui_Label_1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_1, 97 );
lv_obj_set_y( ui_Label_1, 118 );
lv_obj_set_align( ui_Label_1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_1,"H");
lv_obj_set_style_text_color(ui_Label_1, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_1, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_4 = lv_label_create(ui_tab_time);
lv_obj_set_width( ui_Label_4, 29);
lv_obj_set_height( ui_Label_4, 24);
lv_obj_set_x( ui_Label_4, -123 );
lv_obj_set_y( ui_Label_4, 93 );
lv_obj_set_align( ui_Label_4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_4,"0");
lv_obj_set_style_text_color(ui_Label_4, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_4, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_4, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_5 = lv_label_create(ui_tab_time);
lv_obj_set_width( ui_Label_5, 29);
lv_obj_set_height( ui_Label_5, 30);
lv_obj_set_x( ui_Label_5, -123 );
lv_obj_set_y( ui_Label_5, 3 );
lv_obj_set_align( ui_Label_5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_5,"60");
lv_obj_set_style_text_color(ui_Label_5, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_5, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_5, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_6 = lv_label_create(ui_tab_time);
lv_obj_set_width( ui_Label_6, 26);
lv_obj_set_height( ui_Label_6, 26);
lv_obj_set_x( ui_Label_6, -123 );
lv_obj_set_y( ui_Label_6, 50 );
lv_obj_set_align( ui_Label_6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_6,"30");
lv_obj_set_style_text_color(ui_Label_6, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_6, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_6, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_7 = lv_label_create(ui_tab_time);
lv_obj_set_width( ui_Label_7, 29);
lv_obj_set_height( ui_Label_7, 30);
lv_obj_set_x( ui_Label_7, 124 );
lv_obj_set_y( ui_Label_7, 3 );
lv_obj_set_align( ui_Label_7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_7,"99");
lv_obj_set_style_text_color(ui_Label_7, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_7, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_7, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_8 = lv_label_create(ui_tab_time);
lv_obj_set_width( ui_Label_8, 29);
lv_obj_set_height( ui_Label_8, 30);
lv_obj_set_x( ui_Label_8, 124 );
lv_obj_set_y( ui_Label_8, 50 );
lv_obj_set_align( ui_Label_8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_8,"50");
lv_obj_set_style_text_color(ui_Label_8, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_8, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_8, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_9 = lv_label_create(ui_tab_time);
lv_obj_set_width( ui_Label_9, 29);
lv_obj_set_height( ui_Label_9, 30);
lv_obj_set_x( ui_Label_9, 124 );
lv_obj_set_y( ui_Label_9, 93 );
lv_obj_set_align( ui_Label_9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_9,"0");
lv_obj_set_style_text_color(ui_Label_9, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_9, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_9, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_time = lv_img_create(ui_tab_time);
lv_img_set_src(ui_Image_time, &ui_img_images_walking_png_frames_walking_000_png);
lv_obj_set_width( ui_Image_time, LV_SIZE_CONTENT);  /// 110
lv_obj_set_height( ui_Image_time, LV_SIZE_CONTENT);   /// 152
lv_obj_set_x( ui_Image_time, 0 );
lv_obj_set_y( ui_Image_time, 55 );
lv_obj_set_align( ui_Image_time, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_time, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_time, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image_time,160);

ui_tab_weather = lv_tabview_add_tab(ui_Tab_main1, "WEATHER");
lv_obj_clear_flag( ui_tab_weather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_temp = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_temp, 141);
lv_obj_set_height( ui_Label_temp, 50);
lv_obj_set_x( ui_Label_temp, -64 );
lv_obj_set_y( ui_Label_temp, -100 );
lv_obj_set_align( ui_Label_temp, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_temp,"T:00°C");
lv_obj_set_style_text_color(ui_Label_temp, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_temp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_temp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_temp, &ui_font_J60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_hum = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_hum, 135);
lv_obj_set_height( ui_Label_hum, 50);
lv_obj_set_x( ui_Label_hum, 69 );
lv_obj_set_y( ui_Label_hum, -100 );
lv_obj_set_align( ui_Label_hum, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_hum,"H:00%");
lv_obj_set_style_text_color(ui_Label_hum, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_hum, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_hum, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_hum, &ui_font_J60, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_condition = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_condition, 113);
lv_obj_set_height( ui_Label_condition, 28);
lv_obj_set_x( ui_Label_condition, -76 );
lv_obj_set_y( ui_Label_condition, -51 );
lv_obj_set_align( ui_Label_condition, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_condition,"Condition");
lv_obj_set_style_text_color(ui_Label_condition, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_condition, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_condition, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_condition, &ui_font_J35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_windkph = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_windkph, 116);
lv_obj_set_height( ui_Label_windkph, 28);
lv_obj_set_x( ui_Label_windkph, 75 );
lv_obj_set_y( ui_Label_windkph, -50 );
lv_obj_set_align( ui_Label_windkph, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_windkph,"00.0k/h");
lv_obj_set_style_text_color(ui_Label_windkph, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_windkph, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_windkph, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_windkph, &ui_font_J35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_compass = lv_img_create(ui_tab_weather);
lv_img_set_src(ui_Image_compass, &ui_img_images_compass_png);
lv_obj_set_width( ui_Image_compass, LV_SIZE_CONTENT);  /// 33
lv_obj_set_height( ui_Image_compass, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image_compass, -2 );
lv_obj_set_y( ui_Image_compass, -50 );
lv_obj_set_align( ui_Image_compass, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_compass, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_compass, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Image_compass,220);
lv_img_set_zoom(ui_Image_compass,300);

ui_Label_3 = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_3, -93 );
lv_obj_set_y( ui_Label_3, 118 );
lv_obj_set_align( ui_Label_3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_3,"FL");
lv_obj_set_style_text_color(ui_Label_3, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_3, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar_FL = lv_bar_create(ui_tab_weather);
lv_bar_set_range(ui_Bar_FL, 0,60);
lv_obj_set_width( ui_Bar_FL, 15);
lv_obj_set_height( ui_Bar_FL, 108);
lv_obj_set_x( ui_Bar_FL, -96 );
lv_obj_set_y( ui_Bar_FL, 50 );
lv_obj_set_align( ui_Bar_FL, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar_FL, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_FL, lv_color_hex(0x182D0C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_FL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar_FL, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_FL, lv_color_hex(0x00C200), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_FL, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Bar_HI = lv_bar_create(ui_tab_weather);
lv_bar_set_range(ui_Bar_HI, 0,60);
lv_obj_set_width( ui_Bar_HI, 15);
lv_obj_set_height( ui_Bar_HI, 108);
lv_obj_set_x( ui_Bar_HI, 96 );
lv_obj_set_y( ui_Bar_HI, 50 );
lv_obj_set_align( ui_Bar_HI, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar_HI, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_HI, lv_color_hex(0x182D0C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_HI, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar_HI, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_HI, lv_color_hex(0x00C200), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_HI, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label_2 = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label_2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label_2, 100 );
lv_obj_set_y( ui_Label_2, 118 );
lv_obj_set_align( ui_Label_2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_2,"HI");
lv_obj_set_style_text_color(ui_Label_2, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_2, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_10 = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_10, 29);
lv_obj_set_height( ui_Label_10, 24);
lv_obj_set_x( ui_Label_10, -123 );
lv_obj_set_y( ui_Label_10, 93 );
lv_obj_set_align( ui_Label_10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_10,"0");
lv_obj_set_style_text_color(ui_Label_10, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_10, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_10, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_11 = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_11, 26);
lv_obj_set_height( ui_Label_11, 26);
lv_obj_set_x( ui_Label_11, -123 );
lv_obj_set_y( ui_Label_11, 50 );
lv_obj_set_align( ui_Label_11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_11,"30");
lv_obj_set_style_text_color(ui_Label_11, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_11, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_11, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_12 = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_12, 29);
lv_obj_set_height( ui_Label_12, 30);
lv_obj_set_x( ui_Label_12, -123 );
lv_obj_set_y( ui_Label_12, 3 );
lv_obj_set_align( ui_Label_12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_12,"60");
lv_obj_set_style_text_color(ui_Label_12, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_12, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_12, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_13 = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_13, 29);
lv_obj_set_height( ui_Label_13, 30);
lv_obj_set_x( ui_Label_13, 124 );
lv_obj_set_y( ui_Label_13, 3 );
lv_obj_set_align( ui_Label_13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_13,"60");
lv_obj_set_style_text_color(ui_Label_13, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_13, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_13, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_14 = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_14, 29);
lv_obj_set_height( ui_Label_14, 30);
lv_obj_set_x( ui_Label_14, 122 );
lv_obj_set_y( ui_Label_14, 50 );
lv_obj_set_align( ui_Label_14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_14,"30");
lv_obj_set_style_text_color(ui_Label_14, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_14, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_14, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_15 = lv_label_create(ui_tab_weather);
lv_obj_set_width( ui_Label_15, 29);
lv_obj_set_height( ui_Label_15, 30);
lv_obj_set_x( ui_Label_15, 124 );
lv_obj_set_y( ui_Label_15, 93 );
lv_obj_set_align( ui_Label_15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_15,"0");
lv_obj_set_style_text_color(ui_Label_15, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_15, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_15, &ui_font_J30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_weather = lv_img_create(ui_tab_weather);
lv_img_set_src(ui_Image_weather, &ui_img_images_walking_png_frames_walking_000_png);
lv_obj_set_width( ui_Image_weather, LV_SIZE_CONTENT);  /// 110
lv_obj_set_height( ui_Image_weather, LV_SIZE_CONTENT);   /// 152
lv_obj_set_x( ui_Image_weather, 0 );
lv_obj_set_y( ui_Image_weather, 55 );
lv_obj_set_align( ui_Image_weather, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_weather, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_weather, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image_weather,160);

ui_Panel_date = lv_obj_create(ui_stat);
lv_obj_set_width( ui_Panel_date, 270);
lv_obj_set_height( ui_Panel_date, 31);
lv_obj_set_x( ui_Panel_date, 0 );
lv_obj_set_y( ui_Panel_date, 144 );
lv_obj_set_align( ui_Panel_date, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_date, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel_date, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel_date, lv_color_hex(0x203C10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel_date, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel_date, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_date = lv_label_create(ui_Panel_date);
lv_obj_set_width( ui_Label_date, 249);
lv_obj_set_height( ui_Label_date, 30);
lv_obj_set_x( ui_Label_date, 0 );
lv_obj_set_y( ui_Label_date, -2 );
lv_obj_set_align( ui_Label_date, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_date,"Fri 20 Sep 2024");
lv_obj_set_style_text_color(ui_Label_date, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_date, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_date, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_date, &ui_font_J35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel_battery = lv_obj_create(ui_stat);
lv_obj_set_width( ui_Panel_battery, 270);
lv_obj_set_height( ui_Panel_battery, 31);
lv_obj_set_x( ui_Panel_battery, 0 );
lv_obj_set_y( ui_Panel_battery, 182 );
lv_obj_set_align( ui_Panel_battery, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel_battery, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel_battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel_battery, lv_color_hex(0x203C10), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel_battery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel_battery, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel_battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Bar_battery = lv_bar_create(ui_Panel_battery);
lv_bar_set_value(ui_Bar_battery,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar_battery, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar_battery, 230);
lv_obj_set_height( ui_Bar_battery, 19);
lv_obj_set_x( ui_Bar_battery, 14 );
lv_obj_set_y( ui_Bar_battery, 0 );
lv_obj_set_align( ui_Bar_battery, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_Bar_battery, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_battery, lv_color_hex(0x182D0C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_battery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_Bar_battery, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Bar_battery, lv_color_hex(0x00C200), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Bar_battery, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Panel_battery);
lv_img_set_src(ui_Image1, &ui_img_images_battery_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_Image1, -120 );
lv_obj_set_y( ui_Image1, 0 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_tab_data = lv_tabview_add_tab(ui_Tab_main, "DATA");
lv_obj_clear_flag( ui_tab_data, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label_battery = lv_label_create(ui_tab_data);
lv_obj_set_width( ui_Label_battery, 55);
lv_obj_set_height( ui_Label_battery, 31);
lv_obj_set_x( ui_Label_battery, -93 );
lv_obj_set_y( ui_Label_battery, 175 );
lv_obj_set_align( ui_Label_battery, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_battery,"00%");
lv_obj_add_flag( ui_Label_battery, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_color(ui_Label_battery, lv_color_hex(0x00C200), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_battery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_battery, &ui_font_J35, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_data = lv_img_create(ui_tab_data);
lv_img_set_src(ui_Image_data, &ui_img_images_thumpsup_png_frames_thumpsup_000_png);
lv_obj_set_width( ui_Image_data, LV_SIZE_CONTENT);  /// 110
lv_obj_set_height( ui_Image_data, LV_SIZE_CONTENT);   /// 152
lv_obj_set_x( ui_Image_data, 85 );
lv_obj_set_y( ui_Image_data, 123 );
lv_obj_set_align( ui_Image_data, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_data, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_data, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image_data,255);

ui_TextArea_Data = lv_textarea_create(ui_tab_data);
lv_obj_set_width( ui_TextArea_Data, 262);
lv_obj_set_height( ui_TextArea_Data, 382);
lv_obj_set_x( ui_TextArea_Data, 0 );
lv_obj_set_y( ui_TextArea_Data, -11 );
lv_obj_set_align( ui_TextArea_Data, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea_Data,"Placeholder...");
lv_obj_clear_flag( ui_TextArea_Data, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_scrollbar_mode(ui_TextArea_Data, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_color(ui_TextArea_Data, lv_color_hex(0x00AA00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextArea_Data, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_TextArea_Data, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_TextArea_Data, -5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextArea_Data, &ui_font_J35, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_TextArea_Data, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextArea_Data, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextArea_Data, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextArea_Data, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextArea_Data, 0, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Image2 = lv_img_create(ui_tab_data);
lv_img_set_src(ui_Image2, &ui_img_images_vault_logo_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 120
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 58
lv_obj_set_x( ui_Image2, -52 );
lv_obj_set_y( ui_Image2, 142 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
