// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: pip card

#ifndef _PIP_CARD_UI_H
#define _PIP_CARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void thumpsup_Animation( lv_obj_t *TargetObject, int delay);
void walking_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Tab_main;
extern lv_obj_t *ui_stat;
extern lv_obj_t *ui_Panel_date;
extern lv_obj_t *ui_Label_date;
extern lv_obj_t *ui_Panel_battery;
extern lv_obj_t *ui_Bar_battery;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Label_Time;
extern lv_obj_t *ui_Bar_FL;
extern lv_obj_t *ui_Bar_HI;
extern lv_obj_t *ui_Labe01;
extern lv_obj_t *ui_Labe1;
extern lv_obj_t *ui_Img_stat;
extern lv_obj_t *ui_Labe2;
extern lv_obj_t *ui_Labe5;
extern lv_obj_t *ui_data;
extern lv_obj_t *ui_Label_temp;
extern lv_obj_t *ui_Label_hum;
extern lv_obj_t *ui_Bar_Hum;
extern lv_obj_t *ui_Bar_Temp;
extern lv_obj_t *ui_Labe3;
extern lv_obj_t *ui_Labe4;
extern lv_obj_t *ui_Img_data;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_images_button_checked_png);   // assets/Images/button_checked.png
LV_IMG_DECLARE( ui_img_images_battery_png);   // assets/Images/battery.png
LV_IMG_DECLARE( ui_img_images_walking_walking_00_png);   // assets/Images/walking/walking_00.png
LV_IMG_DECLARE( ui_img_images_thumpsup_thumpsup_00_png);   // assets/Images/thumpsup/thumpsup_00.png
LV_IMG_DECLARE( ui_img_images_thumpsup_thumpsup_01_png);   // assets/Images/thumpsup/thumpsup_01.png
LV_IMG_DECLARE( ui_img_images_thumpsup_thumpsup_02_png);   // assets/Images/thumpsup/thumpsup_02.png
LV_IMG_DECLARE( ui_img_images_thumpsup_thumpsup_03_png);   // assets/Images/thumpsup/thumpsup_03.png
LV_IMG_DECLARE( ui_img_images_thumpsup_thumpsup_04_png);   // assets/Images/thumpsup/thumpsup_04.png
LV_IMG_DECLARE( ui_img_images_thumpsup_thumpsup_05_png);   // assets/Images/thumpsup/thumpsup_05.png
LV_IMG_DECLARE( ui_img_images_thumpsup_thumpsup_06_png);   // assets/Images/thumpsup/thumpsup_06.png
LV_IMG_DECLARE( ui_img_images_thumpsup_thumpsup_07_png);   // assets/Images/thumpsup/thumpsup_07.png
LV_IMG_DECLARE( ui_img_images_thumpsup_thumpsup_08_png);   // assets/Images/thumpsup/thumpsup_08.png
LV_IMG_DECLARE( ui_img_images_thumpsup_thumpsup_09_png);   // assets/Images/thumpsup/thumpsup_09.png
LV_IMG_DECLARE( ui_img_images_thumpsup_thumpsup_10_png);   // assets/Images/thumpsup/thumpsup_10.png
LV_IMG_DECLARE( ui_img_images_walking_walking_01_png);   // assets/Images/walking/walking_01.png
LV_IMG_DECLARE( ui_img_images_walking_walking_02_png);   // assets/Images/walking/walking_02.png
LV_IMG_DECLARE( ui_img_images_walking_walking_03_png);   // assets/Images/walking/walking_03.png
LV_IMG_DECLARE( ui_img_images_walking_walking_04_png);   // assets/Images/walking/walking_04.png
LV_IMG_DECLARE( ui_img_images_walking_walking_05_png);   // assets/Images/walking/walking_05.png
LV_IMG_DECLARE( ui_img_images_walking_walking_06_png);   // assets/Images/walking/walking_06.png
LV_IMG_DECLARE( ui_img_images_walking_walking_07_png);   // assets/Images/walking/walking_07.png
LV_IMG_DECLARE( ui_img_images_walking_walking_08_png);   // assets/Images/walking/walking_08.png
LV_IMG_DECLARE( ui_img_images_walking_walking_09_png);   // assets/Images/walking/walking_09.png
LV_IMG_DECLARE( ui_img_images_walking_walking_10_png);   // assets/Images/walking/walking_10.png
LV_IMG_DECLARE( ui_img_images_walking_walking_11_png);   // assets/Images/walking/walking_11.png
LV_IMG_DECLARE( ui_img_images_walking_walking_12_png);   // assets/Images/walking/walking_12.png
LV_IMG_DECLARE( ui_img_images_walking_walking_13_png);   // assets/Images/walking/walking_13.png
LV_IMG_DECLARE( ui_img_images_walking_walking_14_png);   // assets/Images/walking/walking_14.png
LV_IMG_DECLARE( ui_img_images_walking_walking_15_png);   // assets/Images/walking/walking_15.png
LV_IMG_DECLARE( ui_img_images_walking_walking_16_png);   // assets/Images/walking/walking_16.png
LV_IMG_DECLARE( ui_img_images_walking_walking_17_png);   // assets/Images/walking/walking_17.png
LV_IMG_DECLARE( ui_img_images_walking_walking_18_png);   // assets/Images/walking/walking_18.png
LV_IMG_DECLARE( ui_img_images_walking_walking_19_png);   // assets/Images/walking/walking_19.png
LV_IMG_DECLARE( ui_img_images_walking_walking_20_png);   // assets/Images/walking/walking_20.png


LV_FONT_DECLARE( ui_font_J20);
LV_FONT_DECLARE( ui_font_J35);
LV_FONT_DECLARE( ui_font_J60);
LV_FONT_DECLARE( ui_font_J70);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
